-- 보호소에 들어오고나서 중성화한 동물을 조회하는 쿼리문
-- IN과 NOT IN사용
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE IN ('Intact Female', 'Intact Male')
AND O.SEX_UPON_OUTCOME NOT IN ('Intact Female', 'Intact Male')
ORDER BY I.ANIMAL_ID;

-- 테이블의 컬럼 값이 같지 않다는 조건을 이용해서
-- 중성화를 했다가 안 한 상태로 돌릴 수는 없으니
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
ORDER BY I.ANIMAL_ID;