-- 입양을 간 기록은 있는데 보호소에 들어온 기록은 없는 동물 조회.
-- join으로 조회.
SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS AS O 
LEFT JOIN ANIMAL_INS AS I ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL ORDER BY O.ANIMAL_ID;

-- 서브쿼리로 조회.
SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS AS O
WHERE O.ANIMAL_ID NOT IN (SELECT I.ANIMAL_ID FROM ANIMAL_INS AS I)
ORDER BY O.ANIMAL_ID;