-- 0시부터 23시 중 언제 입양이 가장 많이 되었는지 알아보는 쿼리문
-- ANIMAL_OUTS 테이블은 7~19시까지만 존재하기에 재귀를 활용해서 0~23까지 존재하는 테이블 생성
-- 임시 테이블과 ANIMAL_OUTS 테이블 JOIN 하여 문제 해결.
WITH RECURSIVE TEMP AS(
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR+1 FROM TEMP WHERE HOUR <23)

SELECT HOUR, COUNT(A.ANIMAL_ID) AS COUNT FROM TEMP AS T
LEFT JOIN ANIMAL_OUTS AS A ON T.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR ORDER BY T.HOUR;